G = 6.67 * (10 ** -11)  # постоянная г
DELTA_TIME = 100  # один тик
WIDTH, HEIGHT, MENU_SIZE = 700, 700, 200
BALL_SIZE = 20
TAB = 10
BIGGER = 1e4  # TODO: назови нормально дурак
# K = 1  # кпд стен
FPS = 144  # ну фпс для пайгейма
MAX_TRAJECTORY_LEN = 20  # максимальная длина траекторий
TRAJECTORY_SIZE = 3  # pадиус кругов траекторий
TRAJECTORY_UPDATE_TIME = 20
